"""Domain ports — application depends on these; adapters implement them."""

from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Protocol
from uuid import UUID

from app.domain.entities import Drone, Mission, TelemetrySnapshot
from app.domain.value_objects import VehicleCommand, WaypointSpec


class DroneController(Protocol):
    @property
    def drone_id(self) -> UUID: ...

    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def is_connected(self) -> bool: ...

    async def arm(self) -> None: ...

    async def disarm(self) -> None: ...

    async def takeoff(self, altitude_m: float) -> None: ...

    async def land(self) -> None: ...

    async def rtl(self) -> None: ...

    async def hold(self) -> None: ...

    async def execute(self, command: VehicleCommand, altitude_m: float | None = None) -> None: ...


class TelemetryProvider(Protocol):
    def stream(self) -> AsyncIterator[TelemetrySnapshot]: ...


class MissionProvider(Protocol):
    async def upload(self, waypoints: list[WaypointSpec]) -> None: ...

    async def start(self) -> None: ...

    async def pause(self) -> None: ...

    async def clear(self) -> None: ...

    async def progress_percent(self) -> float: ...


class VehiclePort(DroneController, TelemetryProvider, MissionProvider, Protocol):
    """Composite vehicle capability used by the fleet supervisor."""


class DroneRepositoryPort(Protocol):
    async def add(self, drone: Drone) -> Drone: ...

    async def get(self, drone_id: UUID) -> Drone | None: ...

    async def list_all(self) -> list[Drone]: ...

    async def save(self, drone: Drone) -> Drone: ...

    async def delete(self, drone_id: UUID) -> None: ...


class MissionRepositoryPort(Protocol):
    async def add(self, mission: Mission) -> Mission: ...

    async def get(self, mission_id: UUID) -> Mission | None: ...

    async def list_for_drone(self, drone_id: UUID) -> list[Mission]: ...

    async def save(self, mission: Mission) -> Mission: ...


class TelemetryBroadcasterPort(Protocol):
    async def publish(self, telemetry: TelemetrySnapshot) -> None: ...


class TelemetryCachePort(Protocol):
    async def set_latest(self, telemetry: TelemetrySnapshot) -> None: ...

    async def get_latest(self, drone_id: UUID) -> TelemetrySnapshot | None: ...


TelemetryHandler = Callable[[TelemetrySnapshot], Awaitable[None]]
